B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=13
@EndOfDesignText@
Sub Class_Globals
End Sub
Public Sub Initialize
End Sub

Public Sub ChangeLanguage(languageCode As String)
	' English Language
	If languageCode="en" Then
		Starter.Language="en"
		Starter.L_Yes = "Yes"
		Starter.L_No = "No"
		Starter.L_Cancel = "Cancel"
		Starter.L_Error = "Error: "
		Starter.L_Price="Price"
		Starter.L_IQ_Started=" Star "
		Starter.L_InternetError="Please check your internet connection"
		Starter.L_Message = "Message, "
		Starter.L_StartAds = "Show ads, start"
		Starter.L_Rewarded_loaded="A new ad is loaded and ready to play"
		Starter.L_Rewarded_clicked="Ad clicked"
		Starter.L_Rewarded="Ad reward given"
		Starter.L_Rewarded_no="No reward from ad"
		Starter.L_Rewarded_shown="Ad shown"
		Starter.L_Placement = "Placement"
		Starter.L_Reward_Yes = "diamonds added to your diamond wallet."
		Starter.L_Reward_No = "Reward not given."
		Starter.L_TitleMSGExit = "Exit the game?"
		Starter.L_Restart_Game="Restart the game?"
		Starter.L_Do_You_Want_To_Resrart_Game="Do you want to restart the game?"
		Starter.L_TextMSGExit = "Are you sure you want to exit the game?"
		Starter.L_Label_About_Title = "About Rando"
		Starter.L_Label_About_Text = "Hello..." & Chr(10)& Chr(10) _
      &"Wherever you are in the world, be happy"& Chr(10)& Chr(10) _
      &"Welcome to the world of math, Rando"& Chr(10)& Chr(10) _
      &"Rando is a math game suitable for all ages and is run for Alzheimer's disease, and daily use of the game is recommended to everyone. To install and use Rando, no access or permission is required for your phone's software and hardware or an internet connection"&Chr(10) _
      &"So install Rando with peace of mind and enjoy it"& Chr(10)& Chr(10)& Chr(10)& Chr(10) _
      &"Contact us: " & Chr(10)& Chr(10) _
      &"Phone number: 989199899512"& Chr(10) _
      &"Phone number: 989028910101"& Chr(10)& Chr(10) _
      &"Email: mojtaba_asady@ yahoo.com "& Chr(10) _
      &"Email: mojtaba_asady@hotmail.com "& Chr(10) _
      &"Email: mogtaba.asady@gmail.com"& Chr(10)& Chr(10) _
	  &"App Name :"&Application.LabelName&" Ver : "&Application.VersionName
		Starter.L_Label_About_Exit_Text = "Exit"
		Starter.L_Label_About_Help_Text = "About Us"
		Starter.L_Label_About_Shop_Text = "Shop"
		Starter.L_Label_About_Home_Text = "Home"
		Starter.L_Label_Home_Text = "Home"
		Starter.L_Label_Title_Help = "Help"
		Starter.L_Label_Exit_Help_Text = "Exit"
		Starter.L_Label_Shop_Help_Text = "Shop"
		Starter.L_Label_Home_Help_Text = "Home"
		Starter.L_Label_Help_Help_Text = "Help"
		Starter.L_Label_Help_Object_Text_1 = "Exit the game"
		Starter.L_Label_Help_Object_Text_2 = "Single player game"
		Starter.L_Label_Help_Object_Text_3 = "Play with AI"
		Starter.L_Label_Help_Object_Text_4 = "10-question AI challenge"
		Starter.L_Label_Help_Object_Text_5 = "About the Rando game and the development team"
		Starter.L_Label_Help_Object_Text_6 = "Rando game guide"
		Starter.L_Label_Help_Object_Text_7 = "This time tool is for controlling speed"
		Starter.L_Label_Help_Object_Text_8 = "This eye tool is for choosing the correct option"
		Starter.L_Label_Help_Object_Text_9 = "This thunder tool is for changing the answer"
		Starter.L_Label_Help_Object_Text_10 = "Go to the shopping center"
		Starter.L_Label_Help_Object_Text_11 = "Player intelligence level"
		Starter.L_Label_Help_Object_Text_12 = "Diamond wallet, for storing assets earned in the game"
		Starter.L_Label_Help_Object_Text_13 = "Angel of Luck, appears several times a day and gives you free diamonds"
		Starter.L_Label_Help_Object_Text_14 = "Question from Player"
		Starter.L_Label_Help_Object_Text_15 = "Show ad to earn and increase diamond wallet balance"
		Starter.L_Label_Help_Object_Text_16 = "Buy tools for use in the game"
		Starter.L_Label_Help_Object_Text_17 = "Sell tools to increase the diamond wallet balance"
		Starter.L_Label_Application_Name_Menu = "Rando"
		Starter.L_Label_Tab_1 = "Stage"
		Starter.L_Label_Tab_2 = "Settings"
		Starter.L_Label_Tab_3 = "Player"
		Starter.L_Label_Tab_4 = "Shop"
		Starter.L_Label_Exit_Text = "Exit"
		Starter.L_Label_Help_Text = "Help"
		Starter.L_Label_1_Player_Text = "Single Game"
		Starter.L_Label_2_Player_Text = "Doubles Game"
		Starter.L_Label_3_Player_Text = "Challenge with AI"
		Starter.L_Label_Application_Version = "Version: 10.0"
		Starter.L_Label_Title_Level = "Stages"
		Starter.L_Label_Title_Setting = "Settings"
		Starter.L_Label_Setting_MusicBackground = "Background music"
		Starter.L_Label_Setting_MusicEffect = "Music effect"
		Starter.L_Label_Setting_Language = "زبان"
		Starter.L_Spinner_Setting_Language_English = "English"
		Starter.L_Spinner_Setting_Language_Persian = "فارسی"
		Starter.L_Label_ResponsiveSpeed = "Game level"
		Starter.L_Spinner_ResponsiveSpeed_Easy = "Easy"
		Starter.L_Spinner_ResponsiveSpeed_Normal = "Normal"
		Starter.L_Spinner_ResponsiveSpeed_Hard = "Hard"
		Starter.L_Label_Setting_RestartGame = "Restart game"
		Starter.L_Label_Setting_About = "About"
		Starter.L_Label_Setting_Help = "Help"
		Starter.L_Question_type_settings_Title="Question type"
		Starter.L_sum_of_numbers="Sum (+)"
		Starter.L_Subtraction_of_numbers="Subtraction (-)"
		Starter.L_Multiply_numbers="Multiplication (*)"
		Starter.L_Dividing_numbers="Division (/)"
		Starter.L_Random_question="Random (?)"
		Starter.L_Label_Title_UserInformation = "Player information"
		Starter.L_EditText_UserName = "Player 1 name"
		Starter.L_Label_User_Level = "Level"
		Starter.L_Label_MoneyBag = "Wallet"
		Starter.L_Label_User1_Money = "My balance"
		Starter.L_Label_User2_Money = "AI balance"
		Starter.L_Label_User3_Money = "AI challenge amount"
		Starter.L_Label_Level_IQ_Text = "Your intelligence level"
		Starter.L_Label_Level_IQ_Text_AI ="Artificial Intelligence level"
		Starter.L_Label_Tool_Time_Text = "Time"
		Starter.L_Label_Tool_Eye_Text = "Eye"
		Starter.L_Label_Tool_Thunder_Text = "Thunder"
		Starter.L_Label_Title_ShopingCenter = "Shopping center"
		Starter.L_Label_ShopingCenter_Tool_Text_Time = "Time"
		Starter.L_Label_ShopingCenter_Tool_Text_Eye = "Eye"
		Starter.L_Label_ShopingCenter_Tool_Text_Thunder = "Thunder"
		Starter.L_Label_ShopingCenter_Info_ADS = "You can buy tools by watching ads"
		Starter.L_Label_ShopingCenter_Info_MONEY = "You can buy tools with diamonds"
		Starter.L_Label_ShopingCenter_Shop_MoneyBag_MyMoney_Note = "Your wallet balance is in diamonds"
		Starter.L_Label_ShopingCenter_PriceTime_Information = "Buy and sell time"
		Starter.L_Label_ShopingCenter_PriceTime = "Price per unit of time: 200 diamonds"
		Starter.L_Label_ShopingCenter_PriceEye_Information = "Buy and sell eyes"
		Starter.L_Label_ShopingCenter_PriceEye = "Price per unit of eye: 300 diamonds"
		Starter.L_Label_ShopingCenter_PriceThunder_Information = "Buy and sell thunder"
		Starter.L_Label_ShopingCenter_PriceThunder = "Price per unit of thunder: 150 diamonds"
		Starter.L_Label_ShopingCenter_Wallet_MoneyBag_MyMoney_Note = "Your wallet balance is in diamonds"
		Starter.L_Label_ShopingCenter_Wallet_Ads_Note1 = "Earn free diamonds by watching ads"
		Starter.L_Label_ShopingCenter_Wallet_Ads_Note2 = "Watching a full ad is equal to 100 diamonds"
		Starter.L_Label_ShopingCenter_Wallet_PAY_Note1 = "Recharge your diamond wallet with in-app purchases"
		Starter.L_Label_ShopingCenter_Wallet_PAY_Note2 = "Every ten thousand Tomans is equivalent to 1000 diamonds"
		Starter.L_Label_ShopingCenter_Wallet_Chance_Note1 = "Win diamonds randomly"
		Starter.L_Label_ShopingCenter_Wallet_Chance_Note2 = "You can use this feature several times a day"
		Starter.L_ShopingCenter_Shop_Information_Message_1="Ready to buy or sell"
		Starter.L_ShopingCenter_Shop_Information_Message_2="Purchase completed"
		Starter.L_ShopingCenter_Shop_Information_Message_3="Sale completed"
		Starter.L_ShopingCenter_Shop_Information_Message_4 = "You have enough balance to make the purchase"
		Starter.L_ShopingCenter_Shop_Information_Message_5 = "Check your balance"
		Starter.L_Label_FinishGame_Information_1 = "You won"
		Starter.L_Label_FinishGame_Information_2 = "You lost"
		Starter.L_Label_FinishGame_Information_3 = "It's a tie"
		Starter.L_Label_FinishGame_Information_4 = "Rematch"
		Starter.L_Label_FinishGame_RepetLevel_Text = "Repeat"
		Starter.L_Label_FinishGame_NextLevel_Text = "Next level"
		Starter.L_Label_ShopingCenter_Wallet_Chance_RandomPrice = "Time remaining until the return of the lucky angel"
		Starter.L_Label_ShopingCenter_Wallet_Chance_RandomPrice_AddMoney = "Click on the number of diamonds earned now and watch the ad until the end to add diamonds to your wallet"
		Starter.L_Label_Player2_AISearch_Title = "AI search"
		Starter.L_Label_Player2_AISearch_Level = "AI level"
		Starter.L_Label_Player2_AISearch_Home_Text = "Home"
		Starter.L_Label_Player2_AISearch_ChangeAI_Text = "Change AI player"
		Starter.L_Label_Player2_AISearch_PlayGame_Text = "Start game"
		Starter.L_Risk = "Risk"
		Starter.L_PriceRisk = "Amount to risk"
		Starter.L_Confirm_Withdrawal_Amount = "To confirm the withdrawal of the amount from the diamond wallet, start the game"
		Starter.L_Confirmed_Withdrawal_Amount = "The risk amount has been deducted from both players' accounts"
		Starter.L_Confirmed_Reward_Deposited_Into_Wallet = "The risk amount and prize have been deposited into the winner's diamond wallet"
		Starter.L_Label_Player3_ChallengeSearch_Title = "AI challenge search"
		Starter.L_Label_Player3_ChangeChallenge_Text = "Change AI challenge"
		Starter.L_Label_Player3_ChallengeSearch_PlayChallenge_Text = "Start AI challenge"
		Starter.L_Player3_ChallengeSearch_Confirm_Withdrawal_Amount = "To confirm the withdrawal of the amount from the diamond wallet, start the AI challenge"
		Starter.L_Player3_ChallengeSearch_Confirmed_Withdrawal_Amount = "The risk amount has been deducted from your account until the AI challenge result is finalized"
		Starter.L_Challenge_Risk = "AI challenge risk"
		Starter.L_Challenge_PriceRisk = "AI challenge risk amount"
		Starter.L_Price = "Amount"
		Starter.L_ChallengeSearching = "Searching for a new AI challenge..."
		Starter.L_ChallengeSpeed = "AI challenge time: "
		Starter.L_ChallengeSpeed_Sec = " seconds"
		Starter.L_ChallengeSpeed_Elapsed="Elapsed time"
		Starter.L_ChallengeSpeed_Confirmed_Reward_Deposited_Into_Wallet = "The risk amount and prize of the AI challenge have been deposited into the winner's diamond wallet"
		Starter.L_Username_Challenger = "AI: "
		Starter.L_ToastMessageShow_ChangeAI_Info_1 = "You don't have enough diamonds to play with AI, you need at least 100 diamonds"
		Starter.L_ToastMessageShow_ChangeAI_Info_2 = "Each time you execute or change the AI player, 50 diamonds will be deducted"
		Starter.L_ToastMessageShow_ChangeChallenge_Info_1 = "You don't have enough diamonds to take the AI challenge, you need at least 100 diamonds"
		Starter.L_ToastMessageShow_ChangeChallenge_Info_2 = "Each time you execute or change the AI challenge, 50 diamonds will be deducted"
		Starter.L_Titlemsg_RestartGame = "Warning: Confirming this message will reset all game settings, including your diamond wallet balance. Please use this option only in emergencies."
		Starter.L_Textmsg_RestartGame = "Reset to default settings"
		Starter.L_Label_Programmers="Powered by Asady Software development team"

	Else
		'زبان فارسی
		Starter.Language="fa"
		Starter.L_Yes = "بله"
		Starter.L_No = "خیر"
		Starter.L_Cancel = "لغو"
		Starter.L_Error = "خطا : "
		Starter.L_Price="مبلغ"
		Starter.L_IQ_Started=" ستاره "
		Starter.L_InternetError="لطفا اتصال به اینترنت را چک کنید"
		Starter.L_Message = "پیام ، "
		Starter.L_StartAds = "نمایش تبلیغات، شروع"
		Starter.L_Rewarded_loaded="تبلیغ جدید بارگیری شد و آماده پخش است"
		Starter.L_Rewarded_clicked="تبلیغ کلیک شد"
		Starter.L_Rewarded="پاداش تبلیغ داده شد"
		Starter.L_Rewarded_no="تبلیغ بدون پاداش"
		Starter.L_Rewarded_shown="تبلیغ نمایش داده شد"
		Starter.L_Placement = "جایگذاری "
		Starter.L_Reward_Yes = " الماس به کیف الماس شما اضافه شد . "
		Starter.L_Reward_No = "جایزه پرداخت نشد . "
		Starter.L_TitleMSGExit = "خروج از بازی؟"
		Starter.L_Restart_Game="باز راه اندازی مجدد بازی؟"
		Starter.L_Do_You_Want_To_Resrart_Game="آیا می خواهید بازی را دوباره راه اندازی کنید؟"
		Starter.L_TextMSGExit = "آیا مطمئن هستید که می‌خواهید از بازی خارج شوید؟"
		Starter.L_Label_About_Title = "درباره راندو"
		Starter.L_Label_About_Text = "سلام..." & Chr(10)& Chr(10) _
		  &"هر کجای دنیا که هستید، خوش باشید"& Chr(10)& Chr(10) _
		  &"به دنیای ریاضی راندو خوش آمدید "& Chr(10)& Chr(10) _
	   	  &"راندو یک بازی ریاضی است که برای تمام سنین مناسب است و برای بیماری از آلزایمر اجرا می شود و استفاده روزانه از بازی به همه توصیه ها می شود، برای نصب و استفاده از راندو نیازی به دسترسی یا اجازه به نرم افزار و سخت افزار گوشی و اتصال به اینترنت مشخص"&Chr(10) _
		  &"پس با خیال راحت بازی راندو را نصب کنید و از آن لذت ببرید"& Chr(10)& Chr(10)& Chr(10)& Chr(10) _
		  &" تماس با ما : " & Chr(10)& Chr(10) _
		  &"شماره تماس: 989199899512"& Chr(10) _
		  &"شماره تماس: 989028910101"& Chr(10)& Chr(10) _
		  &"ایمیل : mojtaba_asady@ yahoo.com "& Chr(10) _
		  &"ایمیل : mojtaba_asady@hotmail.com "& Chr(10) _
		  &"ایمیل : mogtaba.asady@gmail.com"& Chr(10)& Chr(10) _
		  &"نام برنامه :"&Application.LabelName&" نسخه : "&Application.VersionName
		Starter.L_Label_About_Exit_Text = "خروج"
		Starter.L_Label_About_Help_Text = "درباره ما" 'hjhjhj
		Starter.L_Label_About_Shop_Text = "فروشگاه"
		Starter.L_Label_About_Home_Text = "خانه"
		Starter.L_Label_Home_Text = "خانه"
		Starter.L_Label_Title_Help = "راهنما"
		Starter.L_Label_Exit_Help_Text = "خروج"
		Starter.L_Label_Shop_Help_Text = "فروشگاه"
		Starter.L_Label_Home_Help_Text = "خانه"
		Starter.L_Label_Help_Help_Text = "راهنما"
		Starter.L_Label_Help_Object_Text_1 = "خروج از بازی"
		Starter.L_Label_Help_Object_Text_2 = "بازی یک نفره"
		Starter.L_Label_Help_Object_Text_3 = "بازی با هوش مصنوعی"
		Starter.L_Label_Help_Object_Text_4 = "چالش هوش مصنوعی 10 سوالی"
		Starter.L_Label_Help_Object_Text_5 = "درباره بازی راندو و تیم برنامه‌نویس"
		Starter.L_Label_Help_Object_Text_6 = "راهنمای بازی راندو"
		Starter.L_Label_Help_Object_Text_7 = "این ابزار زمان برای کنترل سرعت است"
		Starter.L_Label_Help_Object_Text_8 = "این ابزار دید برای انتخاب گزینه صحیح است"
		Starter.L_Label_Help_Object_Text_9 = "این ابزار رعد و برق برای تغییر پاسخ جدید است"
		Starter.L_Label_Help_Object_Text_10 = "رفتن به مرکز خرید"
		Starter.L_Label_Help_Object_Text_11 = "سطح هوش بازیکن"
		Starter.L_Label_Help_Object_Text_12 = "کیف پول الماس ، برای ذخیره دارایی های بدست آمده در بازی"
		Starter.L_Label_Help_Object_Text_13 = "فرشته شانس ، روزانه چند بار ظاهر میشود و به شما الماس رایگان میدهد"
		Starter.L_Label_Help_Object_Text_14 = "سوال برنامه از بازیکن "
		Starter.L_Label_Help_Object_Text_15 = "نمایش آگهی ، جهت بدست آوردن و افزایش موجودی کیف پول الماس"
		Starter.L_Label_Help_Object_Text_16 = "خرید ابزار برای استفاده در بازی"
		Starter.L_Label_Help_Object_Text_17 = "فروش ابزار برای افزایش موجودی کیف پول الماس"
		Starter.L_Label_Application_Name_Menu = "راندو"
		Starter.L_Label_Tab_1 = "مرحله"
		Starter.L_Label_Tab_2 = "تنظیمات"
		Starter.L_Label_Tab_3 = "بازیکن"
		Starter.L_Label_Tab_4 = "فروشگاه"
		Starter.L_Label_Exit_Text = "خروج"
		Starter.L_Label_Help_Text = "راهنما"
		Starter.L_Label_1_Player_Text = "بازی یک نفره"
		Starter.L_Label_2_Player_Text = "بازی دو نفره"
		Starter.L_Label_3_Player_Text = "چالش هوش مصنوعی"
		Starter.L_Label_Application_Version = "نسخه: 10.0"
		Starter.L_Label_Title_Level = "مراحل"
		Starter.L_Label_Title_Setting = "تنظیمات"
		Starter.L_Label_Setting_MusicBackground = "موسیقی پس‌زمینه"
		Starter.L_Label_Setting_MusicEffect = "افکت موسیقی"
		Starter.L_Label_Setting_Language = "Language"
		Starter.L_Spinner_Setting_Language_English = "English"
		Starter.L_Spinner_Setting_Language_Persian = "فارسی"
		Starter.L_Label_ResponsiveSpeed = "سطح بازی"
		Starter.L_Spinner_ResponsiveSpeed_Easy = "آسان"
		Starter.L_Spinner_ResponsiveSpeed_Normal = "معمولی"
		Starter.L_Spinner_ResponsiveSpeed_Hard = "سخت"
		Starter.L_Label_Setting_RestartGame = "شروع مجدد بازی"
		Starter.L_Label_Setting_About = "درباره"
		Starter.L_Label_Setting_Help = "آموزش"
		Starter.L_Question_type_settings_Title="نوع سوال"
		Starter.L_sum_of_numbers="جمع (+)"
		Starter.L_Subtraction_of_numbers="تفریق (-)"
		Starter.L_Multiply_numbers="ضرب (*)"
		Starter.L_Dividing_numbers="تقسیم (/)"
		Starter.L_Random_question="تصادفی (?)"
		Starter.L_Label_Title_UserInformation = "اطلاعات بازیکن"
		Starter.L_EditText_UserName = "نام بازیکن ۱"
		Starter.L_Label_User_Level = "مرحله"
		Starter.L_Label_MoneyBag = "کیف پول"
		Starter.L_Label_User1_Money = "موجودی من "
		Starter.L_Label_User2_Money = "موجودی هوش مصنوعی"
		Starter.L_Label_User3_Money = "مبلغ چالش هوش مصنوعی"
		Starter.L_Label_Level_IQ_Text = "سطح هوش شما"
		Starter.L_Label_Level_IQ_Text_AI = "سطح هوش مصنوعی"
		Starter.L_Label_Tool_Time_Text = "زمان"
		Starter.L_Label_Tool_Eye_Text = "چشم"
		Starter.L_Label_Tool_Thunder_Text = "رعد و برق"
		Starter.L_Label_Title_ShopingCenter = "مرکز خرید"
		Starter.L_Label_ShopingCenter_Tool_Text_Time = "زمان"
		Starter.L_Label_ShopingCenter_Tool_Text_Eye = "چشم"
		Starter.L_Label_ShopingCenter_Tool_Text_Thunder = "رعد و برق"
		Starter.L_Label_ShopingCenter_Info_ADS = "شما می‌توانید ابزارها را با مشاهده تبلیغات خریداری کنید"
		Starter.L_Label_ShopingCenter_Info_MONEY = "شما می‌توانید ابزارها را با الماس خریداری کنید"
		Starter.L_Label_ShopingCenter_Shop_MoneyBag_MyMoney_Note = " موجودی کیف پول شما با الماس میباشد"
		Starter.L_Label_ShopingCenter_PriceTime_Information = "خرید و فروش زمان"
		Starter.L_Label_ShopingCenter_PriceTime = "قیمت هر واحد زمان 200 الماس"
		Starter.L_Label_ShopingCenter_PriceEye_Information = "خرید و فروش چشم"
		Starter.L_Label_ShopingCenter_PriceEye = "قیمت هر واحد چشم 300 الماس"
		Starter.L_Label_ShopingCenter_PriceThunder_Information = "خرید و فروش رعد"
		Starter.L_Label_ShopingCenter_PriceThunder = "قیمت هر واحد رعد 150 الماس"
		Starter.L_Label_ShopingCenter_Wallet_MoneyBag_MyMoney_Note = "موجودی کیف پول شما با الماس میباشد"
		Starter.L_Label_ShopingCenter_Wallet_Ads_Note1 = "با دیدن آگهی الماس رایگان دریافت کنید "
		Starter.L_Label_ShopingCenter_Wallet_Ads_Note2 = "دیدن کامل هر آگهی برابر با 100 الماس است"
		Starter.L_Label_ShopingCenter_Wallet_PAY_Note1 = "با خرید درون برنامه ای کیف پول الماس خود را شارژ کنید"
		Starter.L_Label_ShopingCenter_Wallet_PAY_Note2 = "هر ده هزار تومان برابر با 1000 الماس است"
		Starter.L_Label_ShopingCenter_Wallet_Chance_Note1 = "به صورت تصادفی الماس برنده شوید"
		Starter.L_Label_ShopingCenter_Wallet_Chance_Note2 = "روزانه چند بار میتوانید از این امکان استفاده کنید"
		Starter.L_ShopingCenter_Shop_Information_Message_1="آماده خرید یا فروش"
		Starter.L_ShopingCenter_Shop_Information_Message_2="خرید انجام شد"
		Starter.L_ShopingCenter_Shop_Information_Message_3="فروش انجام شد"
		Starter.L_ShopingCenter_Shop_Information_Message_4="شما مبلغ کافی برای خرید را دارید"
		Starter.L_ShopingCenter_Shop_Information_Message_5="موجودی خود را بررسی کنید "
		Starter.L_Label_FinishGame_Information_1="برنده شدید"
		Starter.L_Label_FinishGame_Information_2="شما باختید"
		Starter.L_Label_FinishGame_Information_3="مساوی شد"
		Starter.L_Label_FinishGame_Information_4="تکرار مسابقه"
		Starter.L_Label_FinishGame_RepetLevel_Text="تکرار"
		Starter.L_Label_FinishGame_NextLevel_Text="مرحله بعد"
		Starter.L_Label_ShopingCenter_Wallet_Chance_RandomPrice="زمان باقی مانده تا بازگشت فرشته شانس"
		Starter.L_Label_ShopingCenter_Wallet_Chance_RandomPrice_AddMoney="اکنون روی تعداد الماس بدست آمده کلیک کنید و آگهی را تا پایان مشاهده نمایید تا الماس ها به کیف الماستان اضافه شوند "
		Starter.L_Label_Player2_AISearch_Title="جستجوی هوش مصنوعی"
		Starter.L_Label_Player2_AISearch_Level="سطح هوش مصنوعی"
		Starter.L_Label_Player2_AISearch_Home_Text="خانه"
		Starter.L_Label_Player2_AISearch_ChangeAI_Text="تغییر بازیکن هوش مصنوعی"
		Starter.L_Label_Player2_AISearch_PlayGame_Text="شروع بازی"
		Starter.L_Risk="ریسک"
		Starter.L_PriceRisk="مبلغ قابل ریسک"
		Starter.L_Confirm_Withdrawal_Amount="برای تایید برداشت مبلغ از کیف پول الماس ، بازی را آغاز کنید"
		Starter.L_Confirmed_Withdrawal_Amount="مبلغ ریسک از حساب هر دو بازیکن برداشت شد"
		Starter.L_Confirmed_Reward_Deposited_Into_Wallet="مبلغ ریسک وجایزه به کیف پول الماس برنده واریز شد"
		Starter.L_Label_Player3_ChallengeSearch_Title="جستجوی چالش هوش مصنوعی"
		Starter.L_Label_Player3_ChangeChallenge_Text="تغییر چالش هوش مصنوعی"
		Starter.L_Label_Player3_ChallengeSearch_PlayChallenge_Text="شروع چالش هوش مصنوعی"
		Starter.L_Player3_ChallengeSearch_Confirm_Withdrawal_Amount="برای تایید برداشت مبلغ از کیف پول الماس، چالش هوش مصنوعی را شروع کنید"
		Starter.L_Player3_ChallengeSearch_Confirmed_Withdrawal_Amount="مبلغ خطر از حساب شما تا پایان نتیجه چالش هوش مصنوعی برداشت شد"
		Starter.L_Challenge_Risk="ریسک چالش هوش مصنوعی"
		Starter.L_Challenge_PriceRisk="مبلغ ریسک چالش هوش مصنوعی"
		Starter.L_Price="مبلغ"
		Starter.L_ChallengeSearching="درحال جستجوی چالش هوش مصنوعی جدید..."
		Starter.L_ChallengeSpeed="زمان چالش هوش مصنوعی : "
		Starter.L_ChallengeSpeed_Sec=" ثانیه "
		Starter.L_ChallengeSpeed_Elapsed="زمان طی شده"
		Starter.L_ChallengeSpeed_Confirmed_Reward_Deposited_Into_Wallet="مبلغ ریسک وجایزه چالش هوش مصنوعی به کیف پول الماس برنده واریز شد"
		Starter.L_Username_Challenger = "هوش مصنوعی : "
		Starter.L_ToastMessageShow_ChangeAI_Info_1="مبلغ کافی برای اجرای بازی با هوش مصنوعی را ندارید ، حداقل 100 الماس نیازدازید"
		Starter.L_ToastMessageShow_ChangeAI_Info_2="هر بار اجرا یا تغییر هوش مصنوعی 50 الماس از شما کم میشود"
		Starter.L_ToastMessageShow_ChangeChallenge_Info_1="مبلغ کافی برای اجرای چالش هوش مصنوعی را ندارید ، حداقل 100 الماس نیازدازید"
		Starter.L_ToastMessageShow_ChangeChallenge_Info_2="هر بار اجرا یا تغییر چالش هوش مصنوعی 50 الماس از شما کم میشود"
		Starter.L_Titlemsg_RestartGame="اخطار : با تایید پیام همه تنظیمات بازی از جمله کیف پول الماس شما صفر میگردد ، لطفا فقط در موارد ضروری از  این گزینه استفاده کنید ."
		Starter.L_Textmsg_RestartGame="بازگشت به تنظیمات اولیه"
		Starter.L_Label_Programmers="پشتیبانی شده توسط تیم توسعه نرم افزار Asady"

	End If

End Sub


